export function PrivacyPolicyPage() {
  return (
    <main className="max-w-5xl mx-auto px-6 py-12">
      <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
      
      <p className="text-gray-700 mb-8">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-6">Interpretation and Definitions</h2>
        
        <h3 className="text-2xl font-bold text-gray-900 mb-4">Interpretation</h3>
        <p className="text-gray-700 mb-6">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-2xl font-bold text-gray-900 mb-4">Definitions</h3>
        <p className="text-gray-700 mb-4">For the purposes of this Privacy Policy:</p>
        
        <div className="space-y-4 ml-6">
          <p className="text-gray-700">
            <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
          </p>
          <p className="text-gray-700">
            <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
          </p>
          <p className="text-gray-700">
            <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to honey translations.
          </p>
          <p className="text-gray-700">
            <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
          </p>
          <p className="text-gray-700">
            <strong>Country</strong> refers to: Tamil Nadu, India
          </p>
          <p className="text-gray-700">
            <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
          </p>
          <p className="text-gray-700">
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </p>
          <p className="text-gray-700">
            <strong>Service</strong> refers to the Website.
          </p>
          <p className="text-gray-700">
            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.
          </p>
          <p className="text-gray-700">
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
          </p>
          <p className="text-gray-700">
            <strong>Website</strong> refers to honey translations, accessible from https://honeytranslations.com/
          </p>
          <p className="text-gray-700">
            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-6">Collecting and Using Your Personal Data</h2>
        
        <h3 className="text-2xl font-bold text-gray-900 mb-4">Types of Data Collected</h3>
        
        <h4 className="text-xl font-semibold text-gray-900 mb-3">Personal Data</h4>
        <p className="text-gray-700 mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc ml-8 mb-6 text-gray-700">
          <li>Email address</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-xl font-semibold text-gray-900 mb-3">Usage Data</h4>
        <p className="text-gray-700 mb-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="text-gray-700 mb-4">
          Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
      </section>

      <section className="mb-8">
        <h3 className="text-2xl font-bold text-gray-900 mb-4">Contact Us</h3>
        <p className="text-gray-700 mb-4">
          If you have any questions about this Privacy Policy, You can contact us:
        </p>
        <p className="text-gray-700">
          By visiting this page on our website: <a href="https://honeytranslations.com/" className="text-blue-600 hover:underline">https://honeytranslations.com/</a>
        </p>
      </section>
    </main>
  );
}

export default PrivacyPolicyPage;