/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ftdvxwhjcefwnefzotac"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0ZHZ4d2hqY2Vmd25lZnpvdGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3MTc4MjEsImV4cCI6MjA4MjI5MzgyMX0.XlIcN2wj2PHG05yQfzfVtA2--ujo0d0H6CoUYiVIAUE"