/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ulicqwwunfkvzegqwzhx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsaWNxd3d1bmZrdnplZ3F3emh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4NzYyMDksImV4cCI6MjA5NjQ1MjIwOX0.VNuJwLb4J-4wec8B6kARSTfg8mk20qoTRUdMOd7H1Dw"
